"""users table

Revision ID: 051f0adc089e
Revises: 5ec5a3bc5d50
Create Date: 2021-05-18 14:54:11.874513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051f0adc089e'
down_revision = '5ec5a3bc5d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
